# yaml 配置
version: "3.7"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "33061:13306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "bubble"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis507:
    image: "redis:5.0.7"
    ports:
        - "26379:6379"
  wep_app2:
    build: .
    command: sh -c "./wait-for.sh mysql8019:13306 redis507:6379-- ./wep_app2 ./conf/config.ini"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8888:8080"