name: "web_app"
mode: "dev"
version: "v0.0.1"
port: 8081
start_time: "2021-12-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_backups: 7
  max_age: 30
mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "password"
  dbname: "dbname"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
